version: "3.9"

services:
  pg-sql:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lovable
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data

volumes:
  pg-volume: